# Importações

In [18]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import create_engine, text
from sqlalchemy.types import Numeric

# EDA

## Clientes (JSON)

### Código

In [3]:
df_clientes = pd.read_json('Datasets/clientes_crm.json')
df_clientes.head()

,full_name,location,code,email
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com

In [4]:
df_clientes['location']

0              Aratu (Candeias) , BA
1                        PE , Recife
2                      Rio Grande,RS
3                    AC , Rio Branco
4                 PA - Santarém Novo
5          Fortaleza do Tabocão , TO
6                        PB/Cabedelo
7                       SE - Aracaju
8                   PB - João Pessoa
9                      Santarém / PA
10                 BA - Porto Seguro
11         TO , Fortaleza do Tabocão
12                     PA / Santarém
13                  AM , Itacoatiara
14           Fortaleza do Tabocão,TO
15                      Fortaleza,CE
16                      MS - Corumbá
17                     Santarém - PA
18                       Maceió / AL
19                PA , Santarém Novo
20                     AC,Rio Branco
21                      SE / Aracaju
22                       Santos - SP
23                       Laguna / SC
24                   ES / São Mateus
25                         Manaus/AM
26                       Salvador,BA
27                     PR , Antonina
28                      CE,Fortaleza
29                  Itacoatiara - AM
30                       São Luís,MA
31                 BA - Porto Seguro
32                     Rio Grande/RS
33                    Fortaleza / CE
34                  João Pessoa / PB
35                          Belém/PA
36            MA , Itaqui (São Luís)
37           TO/Fortaleza do Tabocão
38              PE / Suape (Ipojuca)
39                        Corumbá,MS
40             BA / Aratu (Candeias)
41    Vila do Conde (Barcarena) - PA
42              MA/Itaqui (São Luís)
43                    Paranaguá / PR
44                       Santarém,PA
45                         Macapá/AP
46                      RJ / Niterói
47              PE - Suape (Ipojuca)
48                        SE/Aracaju
Name: location, dtype: str

In [5]:
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  49 non-null     str
 1   location   49 non-null     str
 2   code       49 non-null     int64
 3   email      49 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.7 KB

In [6]:
print(df_clientes['full_name'].is_unique)
print(df_clientes['code'].is_unique)
print(df_clientes['location'].is_unique)
print(df_clientes['email'].is_unique)

True
True
False
True

In [7]:
estados_brasil = [
    'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA',
    'MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN',
    'RS','RO','RR','SC','SP','SE','TO'
]

padrao_ou = '|'.join(estados_brasil)
# padrao_regex = r'\b(' + padrao_ou + r')\b'

df_clientes[~df_clientes['location'].str.contains(padrao_ou, na=False)]

Empty DataFrame
Columns: [full_name, location, code, email]
Index: []

In [8]:
df_clientes[df_clientes['code'] == 42]

,full_name,location,code,email
41,Márcia Figueiredo,Vila do Conde (Barcarena) - PA,42,márcia.figueiredo#protonmail.com

In [9]:
df_teste = df_clientes
df_teste['email_valido'] = df_teste['email'].str.match(
    r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$',
    na=False
)
df_teste[~df_teste['email_valido']]

,full_name,location,code,email,email_valido
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com,False
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com,False
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com,False
5,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO",6,coelho.pinheiro.peixoto.antônia.cavalcanti@aol...,False
6,Bianca Barros Rocha Torres Siqueira,PB/Cabedelo,7,torres.barros.rocha.bianca.siqueira#aol.com,False
7,Luiz Alves Pimentel,SE - Aracaju,8,pimentel.alves.luiz#outlook.com,False
8,Lucas Guedes Cunha Lopes,PB - João Pessoa,9,lucas.lopes.guedes.cunha#tutanota.com,False
9,Débora Paiva,Santarém / PA,10,paiva.débora#gmx.com,False
11,Rafael Pereira Barros,"TO , Fortaleza do Tabocão",12,rafael.pereira.barros#zoho.com,False
12,Carlos Guimarães Martins,PA / Santarém,13,martins.guimarães.carlos#hotmail.com,False
14,Carla Lopes Alves Pacheco Rocha,"Fortaleza do Tabocão,TO",15,lopes.alves.pacheco.rocha.carla#yahoo.com,False
16,Luís Paiva Costa Cardoso Coelho,MS - Corumbá,17,costa.paiva.luís.coelho.cardoso@aol.com,False
17,Adriana Guedes Borges Alves Rocha,Santarém - PA,18,rocha.adriana.guedes.borges.alves#protonmail.com,False
18,Renata Lima Gomes Coelho Mendonça,Maceió / AL,19,renata.lima.mendonça.coelho.gomes@icloud.com,False
20,Sandra Rocha Oliveira Soares Peixoto,"AC,Rio Branco",21,peixoto.soares.rocha.oliveira.sandra#yahoo.com,False
21,Daniela Borges Vieira Farias Mendonça,SE / Aracaju,22,borges.vieira.daniela.mendonça.farias#protonma...,False
22,Bruna Mendonça Rodrigues,Santos - SP,23,rodrigues.mendonça.bruna#aol.com,False
23,Carla Peixoto Azevedo Silva Araújo,Laguna / SC,24,peixoto.carla.araújo.silva.azevedo#outlook.com,False
25,Luiz Borges Gomes Araújo,Manaus/AM,26,gomes.araújo.borges.luiz#hotmail.com,False
26,Flávia Nunes Martins Ribeiro Coelho,"Salvador,BA",27,nunes.flávia.coelho.martins.ribeiro@protonmail...,False
29,Victor Araújo Azevedo Tavares Correia,Itacoatiara - AM,30,araújo.tavares.azevedo.victor.correia@gmail.com,False
30,Jéssica Figueiredo Leite Martins,"São Luís,MA",31,jéssica.martins.leite.figueiredo#tutanota.com,False
32,Diego Costa Guedes Cunha,Rio Grande/RS,33,guedes.cunha.costa.diego#outlook.com,False
33,Victor Vieira Nunes Cunha,Fortaleza / CE,34,nunes.cunha.victor.vieira#protonmail.com,False
34,Priscila Martins,João Pessoa / PB,35,martins.priscila#tutanota.com,False
36,Jéssica Pimentel Borges Nunes Teixeira,"MA , Itaqui (São Luís)",37,nunes.borges.teixeira.pimentel.jéssica#yahoo.com,False
37,Mateus Antunes,TO/Fortaleza do Tabocão,38,mateus.antunes#gmail.com,False
39,Lucas Pacheco,"Corumbá,MS",40,pacheco.lucas#aol.com,False
40,Pedro Ribeiro Costa Santos Correia,BA / Aratu (Candeias),41,costa.correia.ribeiro.santos.pedro#yahoo.com,False
41,Márcia Figueiredo,Vila do Conde (Barcarena) - PA,42,márcia.figueiredo#protonmail.com,False
42,Jéssica Farias Cunha,MA/Itaqui (São Luís),43,farias.jéssica.cunha@outlook.com,False
43,Rafael Paiva Vieira,Paranaguá / PR,44,rafael.vieira.paiva#icloud.com,False
44,Amanda Santos Figueiredo Rodrigues Siqueira,"Santarém,PA",45,figueiredo.siqueira.rodrigues.amanda.santos#tu...,False
45,Ana Silva Costa Farias Coelho,Macapá/AP,46,costa.farias.coelho.ana.silva#hotmail.com,False
46,Gabriela Barros Lacerda,RJ / Niterói,47,lacerda.gabriela.barros#tutanota.com,False
47,Letícia Torres Peixoto Oliveira,PE - Suape (Ipojuca),48,torres.oliveira.peixoto.letícia@yahoo.com,False
48,Diego Costa Tavares Antunes,SE/Aracaju,49,costa.tavares.antunes.diego#icloud.com,False

In [10]:
df_teste[
    (df_teste['email_valido'] == False) &
    (~df_teste['email'].str.contains('#', na=False))
]

,full_name,location,code,email,email_valido
5,Antônia Coelho Pinheiro Peixoto Cavalcanti,"Fortaleza do Tabocão , TO",6,coelho.pinheiro.peixoto.antônia.cavalcanti@aol...,False
16,Luís Paiva Costa Cardoso Coelho,MS - Corumbá,17,costa.paiva.luís.coelho.cardoso@aol.com,False
18,Renata Lima Gomes Coelho Mendonça,Maceió / AL,19,renata.lima.mendonça.coelho.gomes@icloud.com,False
26,Flávia Nunes Martins Ribeiro Coelho,"Salvador,BA",27,nunes.flávia.coelho.martins.ribeiro@protonmail...,False
29,Victor Araújo Azevedo Tavares Correia,Itacoatiara - AM,30,araújo.tavares.azevedo.victor.correia@gmail.com,False
42,Jéssica Farias Cunha,MA/Itaqui (São Luís),43,farias.jéssica.cunha@outlook.com,False
47,Letícia Torres Peixoto Oliveira,PE - Suape (Ipojuca),48,torres.oliveira.peixoto.letícia@yahoo.com,False

### Anotações

- full_name, location, code, email
- code funciona como chave primaria para a base de dados
- location pode ser dificil tratar
- Estado é facil de pegar, todos tem
- email precisa consertar # por @
- emails com acento ou cedilha são considerados invalidos, mas são possiveis
- Para cidade talvez remover o estado, as virgulas, barras, parenteses
- depois validar a cidade
- no sql é possivel fazer uma outra tabela pra localização, talvez não precisa 
Ordem e nomeclatura desejada: df_clientes: id_client, full_name, email, state, city

## Custos Importação (JSON)

### Código

In [11]:
df_custos = pd.read_json('Datasets/custos_importacao.json')
df_custos.head()

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105..."
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432..."
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254..."
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909..."
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600..."

In [12]:
df_custos.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     150 non-null    int64
 1   product_name   150 non-null    str
 2   category       150 non-null    str
 3   historic_data  150 non-null    object
dtypes: int64(1), object(1), str(2)
memory usage: 4.8+ KB

In [13]:
df_custos['historic_data'].iloc[0]

[{'start_date': '10/08/2016', 'usd_price': 10583.63},
 {'start_date': '15/06/2018', 'usd_price': 8778.36},
 {'start_date': '25/09/2018', 'usd_price': 8023.87},
 {'start_date': '19/03/2019', 'usd_price': 8772.78},
 {'start_date': '17/01/2020', 'usd_price': 7918.18},
 {'start_date': '17/06/2020', 'usd_price': 6310.01},
 {'start_date': '02/07/2021', 'usd_price': 6586.7},
 {'start_date': '16/05/2022', 'usd_price': 6538.2},
 {'start_date': '28/02/2023', 'usd_price': 6360.91},
 {'start_date': '17/10/2023', 'usd_price': 6574.8},
 {'start_date': '16/02/2024', 'usd_price': 6657.12},
 {'start_date': '22/02/2024', 'usd_price': 6703.2},
 {'start_date': '15/03/2024', 'usd_price': 6633.66},
 {'start_date': '02/08/2024', 'usd_price': 5774.5},
 {'start_date': '08/04/2025', 'usd_price': 5579.75}]

In [14]:
print(df_custos['product_id'].is_unique)
print(df_custos['product_name'].is_unique)
print(df_custos['category'].is_unique)

True
True
False

In [15]:
df_custos['category'].value_counts()

category
eletrônicos    50
propulsão      50
ancoragem      50
Name: count, dtype: int64

### Anotações

- product_id, product_name, category, historic_data
- product_id funciona como chave primaria para a base de dados
- category já está tudo certo
- historic_data precisa de ser transformada
    - atualmente um dicionario grande
    - mudanças de preço ocorrem de maneira aleatoria
    - explodir para fazer varias linhas com start_date e usd_price
    - (lidar com id duplicado)
    - df.explode ou pd.json_normalize
    - na hora de passar para sql criar outra tabela somente de historico de preço
    - talvez criar end_date ou is_current
    - garantir que start_date é uma data
Ordem e nomeclatura desejada: df_custos: id_product, product_name, category, start_date, end_date, usd_price

## Produtos (CSV)

### Código

In [3]:
df_produtos = pd.read_csv('Datasets/produtos_raw.csv')
df_produtos.head()

                             name        price  code        actual_category
0     Transponder AIS Maré Magnum  R$ 33122.52     1            ELETRONICOS
1       Transponder Furuno Marlin  R$ 13998.15     2            ELETRONICOS
2    Radar Furuno Pulse Leviathan   R$ 9024.19     3  E L E T R Ô N I C O S
3       Rádio AIS Hydro Tidal Zen   R$ 3381.88     4            Eletrunicos
4  Piloto Automático Furuno Storm  R$ 23669.01     5            Eletronicoz

In [4]:
df_produtos.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    str
 1   price            157 non-null    str
 2   code             157 non-null    int64
 3   actual_category  157 non-null    str
dtypes: int64(1), str(3)
memory usage: 5.0 KB

In [5]:
df_produtos['code'].is_unique

False

In [6]:
df_produtos[df_produtos['code'].duplicated(keep=False)].sort_values('name')

,name,price,code,actual_category
124,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorageM
150,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorajeM
151,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,Ancoragen
131,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragem
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragi
36,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,E L E T R Ô N I C O S
37,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,ELEtRÔNICOS
62,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,P R O P U L S Ã O
63,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Propução
64,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,propulsão
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Prop

In [7]:
(df_produtos['code'].value_counts() > 1).sum()

np.int64(4)

In [8]:
df_produtos[df_produtos['code'] == 29]

                 name        price  code actual_category
28  Rádio Simrad Orca  R$ 36510.34    29     Eletrunicos

In [9]:
df_produtos['actual_category'].value_counts()

actual_category
AncorageM                9
Propução                 8
Ancoraguem               8
Eletronicoz              7
eletrônicos              7
ELETRONICOS              6
E L E T R Ô N I C O S    6
PROPULSAO                6
P R O P U L S Ã O        6
propulsão                6
Eletrunicos              5
eLeTrÔnIcOs              5
Propulção                5
Prop                     5
Propulssão               5
Encoragem                5
Ancorajm                 5
A N C O R A G E M        5
aNcOrAgEm                5
Eletrônicos              4
propulsao                4
eletronicos              3
EletrônicoS              3
Propulçao                3
Ancoragem                3
Ancorajem                3
Eletroniscos             2
Eletronicos              2
pRoPuLsÃo                2
Propulsam                2
AnCoRaGeM                2
ancoragem                2
Ancorajen                2
ELEtRÔNICOS              1
PrOpUlSãO                1
ANCORAGEM                1
Encoragi                 1
AncorajeM                1
Ancoragen                1
Name: count, dtype: int64

In [10]:
df_produtos['actual_category'].value_counts()[df_produtos['actual_category'].value_counts() <= 3]

actual_category
eletronicos     3
EletrônicoS     3
Propulçao       3
Ancoragem       3
Ancorajem       3
Eletroniscos    2
Eletronicos     2
pRoPuLsÃo       2
Propulsam       2
AnCoRaGeM       2
ancoragem       2
Ancorajen       2
ELEtRÔNICOS     1
PrOpUlSãO       1
ANCORAGEM       1
Encoragi        1
AncorajeM       1
Ancoragen       1
Name: count, dtype: int64

### Anotações

- name, price, code, actual_category
- Nenhum Null
- Code funciona como chave primaria MAS precisa tirar duplicadas
- price esta com RS na frente, mudar nome para BRL e valores para float
- Usar categoria que mais aparece para organizar?
    - nao precisa, custos_importaçao tem as 3 categorias certas
- Categoria trabalhão - Escrito errado, com espaço, etc.
- Talvez uma IA para prever categoria
- Possibilidades: 
    - fazer clusters e depois nomea-los
    - Usar rapidfuzz com cateforias que sei pra classificar mais provavel
        - talvez chegar confiança abaixo de 70
    - N-grams para dividir a palavra e acertar erro de digitação (favorita)
- Categorias Corretas: ancoragem, eletrônicos, propulsão
- IMPORTANTE: normalizar antes de tudo, tirar acentos, tirar espaços, tudo minusculo
Ordem e nomeclatura desejada: df_produtos: id_product, product_name, category, price

## Vendas (CSV)

### Código

In [9]:
df_vendas = pd.read_csv('Datasets/vendas_2023_2024.csv')
df_vendas.head()

   id  id_client  id_product  qtd     total   sale_date
0   0         42         105   11    3405.0  2023-09-10
1   1          3         136    9   16873.9  15-09-2024
2   2         25         139    7    9475.3  2024-08-13
3   4         20          23    5   55893.0  2023-02-03
4   5          8          57    4  451403.9  2024-02-12

In [10]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9895 non-null   int64
 1   id_client   9895 non-null   int64
 2   id_product  9895 non-null   int64
 3   qtd         9895 non-null   int64
 4   total       9895 non-null   float64
 5   sale_date   9895 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 464.0 KB

In [11]:
df_vendas['id'].is_unique

True

### Anotações

- id, id_client, id_product, qtd, total, sale_date
- id chave primaria da tabela
- sem dados nulls
- precisa transformar sale_date em data ao inves de string
- id produto e cliente parece consistente com os codigos dos outros csvs
- conferir mais valores para garantir
- (atualmente não esta pronto para trocas de preços)
Ordem e nomeclatura desejada: df_vendas: id_venda, id_client, id_product, qtd, total, sale_date

# Tratamento de Dados

dfs brutos:
df_clientes = full_name, location, code, email
df_custos = product_id, product_name, category, historic_data
df_produtos = name, price, code, actual_category
df_vendas = id, id_client, id_product, qtd, total, sale_date

mudanças:
df_clientes: id_client, full_name, email, city, state
location -> state, city

df_custos: id_product, product_name, category, start_date, end_date, usd_price 
historic_data -> start_date, end_date, usd_price

df_produtos: id_product, product_name, category, brl_price
category = ancoragem, eletrônicos, propulsão

df_vendas: id_sale, id_client, id_product, qtd, brl_total, sale_date

## Clientes

- full_name, location, code, email
- code funciona como chave primaria para a base de dados
- location pode ser dificil tratar
- Estado é facil de pegar, todos tem
- Para cidade talvez remover o estado, as virgulas, barras, parenteses
- depois validar a cidade
- no sql é possivel fazer uma outra tabela pra localização, talvez não precisa 
Ordem e nomeclatura desejada: df_clientes: id_client, full_name, email, state, city

In [27]:
df_clientes.head()

,full_name,location,code,email,email_valido
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,True
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,True
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com,False
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com,False
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com,False

In [28]:
estados_brasil = [
    'AC','AL','AP','AM','BA','CE','DF','ES','GO','MA',
    'MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN',
    'RS','RO','RR','SC','SP','SE','TO'
]

padrao_regex = r'\b(' + '|'.join(estados_brasil) + r')\b'

df_clientes['state'] = df_clientes['location'].str.extract(padrao_regex)
df_clientes.head()

,full_name,location,code,email,email_valido,state
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,True,BA
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,True,PE
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com,False,RS
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com,False,AC
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com,False,PA

In [29]:
df_clientes['city_raw'] = (
    df_clientes['location']
    .str.replace(padrao_regex, '', regex=True)
)
df_clientes.head()

,full_name,location,code,email,email_valido,state,city_raw
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,True,BA,"Aratu (Candeias) ,"
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,True,PE,", Recife"
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com,False,RS,"Rio Grande,"
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com,False,AC,", Rio Branco"
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com,False,PA,- Santarém Novo

In [30]:
# Talvez considerar que entre os parenteses está a cidade certa
df_clientes['city'] = (
    df_clientes['city_raw']
    .str.replace(r'[-,/\|()]', ' ', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
    .str.title()
)

df_clientes['city'].sort_values().unique()

<StringArray>
[               'Antonina',                 'Aracaju',
          'Aratu Candeias',                   'Belém',
                'Cabedelo',                 'Corumbá',
               'Fortaleza',    'Fortaleza Do Tabocão',
             'Itacoatiara',         'Itaqui São Luís',
             'João Pessoa',                  'Laguna',
                  'Macapá',                  'Maceió',
                  'Manaus',                 'Niterói',
               'Paranaguá',            'Porto Seguro',
                  'Recife',              'Rio Branco',
              'Rio Grande',                'Salvador',
                'Santarém',           'Santarém Novo',
                  'Santos',           'Suape Ipojuca',
                'São Luís',              'São Mateus',
 'Vila Do Conde Barcarena']
Length: 29, dtype: str

In [31]:
df_clientes['email'] = df_clientes['email'].str.replace('#', '@')
df_clientes['email']

0                 femininos.oliveira.antunes@icloud.com
1      nunes.fernanda.soares.azevedo.vieira@outlook.com
2              farias.teixeira.daniel.ribeiro@gmail.com
3                              thiago.moreira@gmail.com
4                              pedro.freitas@icloud.com
5     coelho.pinheiro.peixoto.antônia.cavalcanti@aol...
6           torres.barros.rocha.bianca.siqueira@aol.com
7                       pimentel.alves.luiz@outlook.com
8                 lucas.lopes.guedes.cunha@tutanota.com
9                                  paiva.débora@gmx.com
10                     torres.monteiro.victor@gmail.com
11                       rafael.pereira.barros@zoho.com
12                 martins.guimarães.carlos@hotmail.com
13              vieira.silva.amaral.gabriela@icloud.com
14            lopes.alves.pacheco.rocha.carla@yahoo.com
15                      renata.pacheco.cardoso@zoho.com
16              costa.paiva.luís.coelho.cardoso@aol.com
17     rocha.adriana.guedes.borges.alves@protonmail.com
18         renata.lima.mendonça.coelho.gomes@icloud.com
19                                 silva.bruno@zoho.com
20       peixoto.soares.rocha.oliveira.sandra@yahoo.com
21    borges.vieira.daniela.mendonça.farias@protonma...
22                     rodrigues.mendonça.bruna@aol.com
23       peixoto.carla.araújo.silva.azevedo@outlook.com
24    femininos.antunes.amaral.lopes.ribeiro@icloud.com
25                 gomes.araújo.borges.luiz@hotmail.com
26    nunes.flávia.coelho.martins.ribeiro@protonmail...
27                          rodrigues.bianca@icloud.com
28              moraes.nunes.gabriela.macedo@icloud.com
29      araújo.tavares.azevedo.victor.correia@gmail.com
30        jéssica.martins.leite.figueiredo@tutanota.com
31    antunes.coelho.batista.teixeira.daniela@hotmai...
32                 guedes.cunha.costa.diego@outlook.com
33             nunes.cunha.victor.vieira@protonmail.com
34                        martins.priscila@tutanota.com
35                   ribeiro.francisca.pinheiro@aol.com
36     nunes.borges.teixeira.pimentel.jéssica@yahoo.com
37                             mateus.antunes@gmail.com
38                     oliveira.renata.siqueira@aol.com
39                                pacheco.lucas@aol.com
40         costa.correia.ribeiro.santos.pedro@yahoo.com
41                     márcia.figueiredo@protonmail.com
42                     farias.jéssica.cunha@outlook.com
43                       rafael.vieira.paiva@icloud.com
44    figueiredo.siqueira.rodrigues.amanda.santos@tu...
45            costa.farias.coelho.ana.silva@hotmail.com
46                 lacerda.gabriela.barros@tutanota.com
47            torres.oliveira.peixoto.letícia@yahoo.com
48               costa.tavares.antunes.diego@icloud.com
Name: email, dtype: str

In [32]:
df_clientes.head()

,full_name,location,code,email,email_valido,state,city_raw,city
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com,True,BA,"Aratu (Candeias) ,",Aratu Candeias
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com,True,PE,", Recife",Recife
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro@gmail.com,False,RS,"Rio Grande,",Rio Grande
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira@gmail.com,False,AC,", Rio Branco",Rio Branco
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas@icloud.com,False,PA,- Santarém Novo,Santarém Novo

In [33]:
df_clientes_limpo = (
    df_clientes
    .rename(columns={'code': 'id_client'})
    [['id_client', 'full_name', 'email', 'city', 'state']]
)
df_clientes_limpo.head()

,id_client,full_name,email,city,state
0,1,Femininos Oliveira Antunes,femininos.oliveira.antunes@icloud.com,Aratu Candeias,BA
1,2,Fernanda Azevedo Soares Nunes Vieira,nunes.fernanda.soares.azevedo.vieira@outlook.com,Recife,PE
2,3,Daniel Farias Ribeiro Teixeira,farias.teixeira.daniel.ribeiro@gmail.com,Rio Grande,RS
3,4,Thiago Moreira,thiago.moreira@gmail.com,Rio Branco,AC
4,5,Pedro Freitas,pedro.freitas@icloud.com,Santarém Novo,PA

In [34]:
df_clientes_limpo.info()

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_client  49 non-null     int64
 1   full_name  49 non-null     str
 2   email      49 non-null     str
 3   city       49 non-null     str
 4   state      49 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.0 KB

## Custos Importação

- product_id, product_name, category, historic_data
- product_id funciona como chave primaria para a base de dados
- category já está tudo certo
- historic_data precisa de ser transformada
    - atualmente um dicionario grande
    - mudanças de preço ocorrem de maneira aleatoria
    - explodir para fazer varias linhas com start_date e usd_price
    - (lidar com id duplicado)
    - df.explode ou pd.json_normalize
    - na hora de passar para sql criar outra tabela somente de historico de preço
    - talvez criar end_date ou is_current
    - garantir que start_date é uma data
Ordem e nomeclatura desejada: df_custos: id_product, product_name, category, start_date, end_date, usd_price

In [35]:
df_custos.head()

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105..."
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432..."
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254..."
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909..."
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600..."

In [36]:
df_custos = df_custos.explode('historic_data')
df_custos = pd.concat([
    df_custos.drop(columns=['historic_data']),
    df_custos['historic_data'].apply(pd.Series)
], axis=1)
df_custos.head()

   product_id                 product_name     category  start_date  usd_price
0           1  Transponder AIS Maré Magnum  eletrônicos  10/08/2016   10583.63
0           1  Transponder AIS Maré Magnum  eletrônicos  15/06/2018    8778.36
0           1  Transponder AIS Maré Magnum  eletrônicos  25/09/2018    8023.87
0           1  Transponder AIS Maré Magnum  eletrônicos  19/03/2019    8772.78
0           1  Transponder AIS Maré Magnum  eletrônicos  17/01/2020    7918.18

In [37]:
df_custos['start_date'] = pd.to_datetime(df_custos['start_date'], dayfirst=True)
df_custos['end_date'] = df_custos.groupby('product_id')['start_date'].shift(-1) - pd.Timedelta(days=1)
df_custos.head()

,product_id,product_name,category,start_date,usd_price,end_date
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,10583.63,2018-06-14
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-06-15,8778.36,2018-09-24
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-09-25,8023.87,2019-03-18
0,1,Transponder AIS Maré Magnum,eletrônicos,2019-03-19,8772.78,2020-01-16
0,1,Transponder AIS Maré Magnum,eletrônicos,2020-01-17,7918.18,2020-06-16

In [38]:
df_custos_limpo = (
    df_custos
    .rename(columns={'product_id': 'id_product'})
    [['id_product', 'product_name', 'category', 'start_date', 'end_date', 'usd_price']]
)
df_custos_limpo.head()

,id_product,product_name,category,start_date,end_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,2018-06-14,10583.63
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-06-15,2018-09-24,8778.36
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-09-25,2019-03-18,8023.87
0,1,Transponder AIS Maré Magnum,eletrônicos,2019-03-19,2020-01-16,8772.78
0,1,Transponder AIS Maré Magnum,eletrônicos,2020-01-17,2020-06-16,7918.18

## Produtos

In [13]:
df_produtos['actual_category'].sort_values().unique()

<StringArray>
[    'A N C O R A G E M',             'ANCORAGEM',             'AnCoRaGeM',
             'AncorageM',             'Ancoragem',             'Ancoragen',
            'Ancoraguem',             'AncorajeM',             'Ancorajem',
             'Ancorajen',              'Ancorajm', 'E L E T R Ô N I C O S',
           'ELETRONICOS',           'ELEtRÔNICOS',           'Eletronicos',
           'Eletronicoz',          'Eletroniscos',           'Eletrunicos',
           'EletrônicoS',           'Eletrônicos',             'Encoragem',
              'Encoragi',     'P R O P U L S Ã O',             'PROPULSAO',
             'PrOpUlSãO',                  'Prop',             'Propulsam',
            'Propulssão',             'Propulçao',             'Propulção',
              'Propução',             'aNcOrAgEm',             'ancoragem',
           'eLeTrÔnIcOs',           'eletronicos',           'eletrônicos',
             'pRoPuLsÃo',             'propulsao',             'propulsão']
Length: 39, dtype: str

In [14]:
df_produtos_limpo = df_produtos.rename(columns={'code': 'id_product', 'name': 'product_name'})
df_produtos_limpo['actual_category'] = (
    df_produtos_limpo['actual_category']
    .str.lower()
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
    .str.replace(' ', '', regex=False)
)
df_produtos_limpo['actual_category'].sort_values().unique()

<StringArray>
[   'ancoragem',    'ancoragen',   'ancoraguem',    'ancorajem',
    'ancorajen',     'ancorajm',  'eletronicos',  'eletronicoz',
 'eletroniscos',  'eletrunicos',    'encoragem',     'encoragi',
         'prop',     'propucao',    'propulcao',    'propulsam',
    'propulsao',   'propulssao']
Length: 18, dtype: str

In [15]:
categories = ['ancoragem', 'eletronicos', 'propulsao']
vectorizer = TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4))
train_texts = categories + df_produtos_limpo['actual_category'].unique().tolist()
vectorizer.fit(train_texts)
target_vectors = vectorizer.transform(categories)
values_vectors = vectorizer.transform(df_produtos_limpo['actual_category'])
similarity = cosine_similarity(values_vectors, target_vectors)

df_produtos_limpo['category_predicted'] = [categories[i] for i in np.argmax(similarity, axis=1)]
df_produtos_limpo['confidence'] = np.max(similarity, axis=1)

df_produtos_limpo.head()

,product_name,price,id_product,actual_category,category_predicted,confidence
0,Transponder AIS Maré Magnum,R$ 33122.52,1,eletronicos,eletronicos,1.000000
1,Transponder Furuno Marlin,R$ 13998.15,2,eletronicos,eletronicos,1.000000
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,eletronicos,eletronicos,1.000000
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,eletrunicos,eletronicos,0.632087
4,Piloto Automático Furuno Storm,R$ 23669.01,5,eletronicoz,eletronicos,0.734737

In [16]:
df_produtos_limpo[df_produtos_limpo['confidence'] < 0.5].sort_values('confidence')

,product_name,price,id_product,actual_category,category_predicted,confidence
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,encoragi,ancoragem,0.300532
53,Motor Elétrico Torqeedo Zen Titan Hydra 129HP,R$ 53675.01,53,prop,propulsao,0.349974
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,prop,propulsao,0.349974
59,Motor Diesel Yanmar Hydro Magnum Boost 267HP,R$ 87166.14,59,prop,propulsao,0.349974
102,Motor Elétrico Honda Flux Ultra 273HP,R$ 107266.66,99,prop,propulsao,0.349974
83,Motor de Popa Volvo Maré 69HP,R$ 129223.84,80,prop,propulsao,0.349974
140,Cabo de Nylon Danforth Titan Poseidon,R$ 1644.51,135,ancorajen,ancoragem,0.373543
141,Cabo de Nylon Bruce Flux Hydro,R$ 1973.5,136,ancorajen,ancoragem,0.373543
80,Motor Diesel Tohatsu Vector 197HP,R$ 44704.67,77,propucao,propulsao,0.425695
79,Motor Diesel Honda Aero 205HP,R$ 148198.23,76,propucao,propulsao,0.425695
95,Motor Elétrico Yamaha Nautic Kraken 133HP,R$ 88854.1,92,propucao,propulsao,0.425695
94,Motor Elétrico Tohatsu Zenith Oceanic 113HP,R$ 134886.02,91,propucao,propulsao,0.425695
97,Motor de Popa Volvo Magnum 276HP,R$ 40750.84,94,propucao,propulsao,0.425695
75,Motor de Popa Volvo Hydro Dash 256HP,R$ 99664.64,72,propucao,propulsao,0.425695
72,Motor de Popa Torqeedo Ultra Impulse 292HP,R$ 45265.02,69,propucao,propulsao,0.425695
63,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,propucao,propulsao,0.425695
145,Boia de Arqueamento Bruce Dash Titan Pulse,R$ 3134.58,140,ancorajm,ancoragem,0.436665
127,Cabo de Nylon Danforth Orca Aero,R$ 2777.07,123,ancorajm,ancoragem,0.436665
109,Âncora Danforth Nitro Titan Vox,R$ 4384.87,106,ancorajm,ancoragem,0.436665
144,Boia de Arqueamento Danforth Torque,R$ 1424.88,139,ancorajm,ancoragem,0.436665
147,Âncora Danforth Vector Evo,R$ 826.41,142,ancorajm,ancoragem,0.436665
122,Âncora Bruce Aqua,R$ 3255.82,119,ancorajem,ancoragem,0.493881
150,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,ancorajem,ancoragem,0.493881
154,Âncora Delta Force Barracuda Mako,R$ 4785.56,148,ancorajem,ancoragem,0.493881
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,ancorajem,ancoragem,0.493881

In [17]:
mapa_categorias = {
    'ancoragem': 'ancoragem',
    'eletronicos': 'eletrônicos',
    'propulsao': 'propulsão'
}
df_produtos_limpo['category'] = df_produtos_limpo['category_predicted'].map(mapa_categorias)
df_produtos_limpo.head()

,product_name,price,id_product,actual_category,category_predicted,confidence,category
0,Transponder AIS Maré Magnum,R$ 33122.52,1,eletronicos,eletronicos,1.000000,eletrônicos
1,Transponder Furuno Marlin,R$ 13998.15,2,eletronicos,eletronicos,1.000000,eletrônicos
2,Radar Furuno Pulse Leviathan,R$ 9024.19,3,eletronicos,eletronicos,1.000000,eletrônicos
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,eletrunicos,eletronicos,0.632087,eletrônicos
4,Piloto Automático Furuno Storm,R$ 23669.01,5,eletronicoz,eletronicos,0.734737,eletrônicos

In [18]:
df_produtos_limpo.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_name        157 non-null    str
 1   price               157 non-null    str
 2   id_product          157 non-null    int64
 3   actual_category     157 non-null    str
 4   category_predicted  157 non-null    str
 5   confidence          157 non-null    float64
 6   category            157 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 8.7 KB

In [19]:
df_produtos_limpo['price'] = (
    df_produtos_limpo['price']
    .str.replace('R$', '', regex=False)
    .str.strip()
    .astype(float)
)
df_produtos_limpo.head()

,product_name,price,id_product,actual_category,category_predicted,confidence,category
0,Transponder AIS Maré Magnum,33122.52,1,eletronicos,eletronicos,1.000000,eletrônicos
1,Transponder Furuno Marlin,13998.15,2,eletronicos,eletronicos,1.000000,eletrônicos
2,Radar Furuno Pulse Leviathan,9024.19,3,eletronicos,eletronicos,1.000000,eletrônicos
3,Rádio AIS Hydro Tidal Zen,3381.88,4,eletrunicos,eletronicos,0.632087,eletrônicos
4,Piloto Automático Furuno Storm,23669.01,5,eletronicoz,eletronicos,0.734737,eletrônicos

In [20]:
df_produtos_limpo.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_name        157 non-null    str
 1   price               157 non-null    float64
 2   id_product          157 non-null    int64
 3   actual_category     157 non-null    str
 4   category_predicted  157 non-null    str
 5   confidence          157 non-null    float64
 6   category            157 non-null    str
dtypes: float64(2), int64(1), str(4)
memory usage: 8.7 KB

In [21]:
df_produtos_limpo = (
    df_produtos_limpo
    .rename(columns={'price': 'brl_price'})
    [['id_product', 'product_name', 'category','brl_price']]
)
df_produtos_limpo.head()

   id_product                    product_name     category  brl_price
0           1     Transponder AIS Maré Magnum  eletrônicos   33122.52
1           2       Transponder Furuno Marlin  eletrônicos   13998.15
2           3    Radar Furuno Pulse Leviathan  eletrônicos    9024.19
3           4       Rádio AIS Hydro Tidal Zen  eletrônicos    3381.88
4           5  Piloto Automático Furuno Storm  eletrônicos   23669.01

In [22]:
df_produtos_limpo.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_product    157 non-null    int64
 1   product_name  157 non-null    str
 2   category      157 non-null    str
 3   brl_price     157 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 5.0 KB

In [23]:
df_produtos_limpo = df_produtos_limpo.drop_duplicates()

In [24]:
df_produtos_limpo.info()

<class 'pandas.DataFrame'>
Index: 150 entries, 0 to 156
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_product    150 non-null    int64
 1   product_name  150 non-null    str
 2   category      150 non-null    str
 3   brl_price     150 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 5.9 KB

In [49]:
df_produtos_limpo[df_produtos_limpo['id_product'].duplicated(keep=False)].sort_values('product_name')

Empty DataFrame
Columns: [id_product, product_name, category, brl_price]
Index: []

## Vendas

In [5]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9895 non-null   int64
 1   id_client   9895 non-null   int64
 2   id_product  9895 non-null   int64
 3   qtd         9895 non-null   int64
 4   total       9895 non-null   float64
 5   sale_date   9895 non-null   str
dtypes: float64(1), int64(4), str(1)
memory usage: 464.0 KB

In [6]:
df_vendas['sale_date']

0       2023-09-10
1       15-09-2024
2       2024-08-13
3       2023-02-03
4       2024-02-12
           ...
9890    11-03-2023
9891    17-09-2023
9892    20-06-2023
9893    23-10-2024
9894    15-06-2023
Name: sale_date, Length: 9895, dtype: str

In [12]:
vendas_iso = pd.to_datetime(df_vendas['sale_date'], format='%Y-%m-%d', errors='coerce')
vendas_br = pd.to_datetime(df_vendas['sale_date'], format='%d-%m-%Y', errors='coerce')

df_vendas['sale_date'] = vendas_iso.fillna(vendas_br)
df_vendas[df_vendas['sale_date'].isna()]

Empty DataFrame
Columns: [id, id_client, id_product, qtd, total, sale_date]
Index: []

In [13]:
df_vendas[df_vendas['sale_date'] == '2024-12-09']

Empty DataFrame
Columns: [id, id_client, id_product, qtd, total, sale_date]
Index: []

In [14]:
df_vendas_limpo = df_vendas.rename(columns={'id': 'id_sale', 'total': 'brl_total'})
df_vendas_limpo.head()

   id_sale  id_client  id_product  qtd  brl_total  sale_date
0        0         42         105   11     3405.0 2023-09-10
1        1          3         136    9    16873.9 2024-09-15
2        2         25         139    7     9475.3 2024-08-13
3        4         20          23    5    55893.0 2023-02-03
4        5          8          57    4   451403.9 2024-02-12

In [16]:
df_vendas_limpo.info()

<class 'pandas.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_sale     9895 non-null   int64
 1   id_client   9895 non-null   int64
 2   id_product  9895 non-null   int64
 3   qtd         9895 non-null   int64
 4   brl_total   9895 non-null   float64
 5   sale_date   9895 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(4)
memory usage: 464.0 KB

## Checando

In [54]:
df_clientes_limpo.head()

,id_client,full_name,email,city,state
0,1,Femininos Oliveira Antunes,femininos.oliveira.antunes@icloud.com,Aratu Candeias,BA
1,2,Fernanda Azevedo Soares Nunes Vieira,nunes.fernanda.soares.azevedo.vieira@outlook.com,Recife,PE
2,3,Daniel Farias Ribeiro Teixeira,farias.teixeira.daniel.ribeiro@gmail.com,Rio Grande,RS
3,4,Thiago Moreira,thiago.moreira@gmail.com,Rio Branco,AC
4,5,Pedro Freitas,pedro.freitas@icloud.com,Santarém Novo,PA

In [55]:
df_custos_limpo.head()

,id_product,product_name,category,start_date,end_date,usd_price
0,1,Transponder AIS Maré Magnum,eletrônicos,2016-08-10,2018-06-14,10583.63
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-06-15,2018-09-24,8778.36
0,1,Transponder AIS Maré Magnum,eletrônicos,2018-09-25,2019-03-18,8023.87
0,1,Transponder AIS Maré Magnum,eletrônicos,2019-03-19,2020-01-16,8772.78
0,1,Transponder AIS Maré Magnum,eletrônicos,2020-01-17,2020-06-16,7918.18

In [56]:
df_produtos_limpo.head()

   id_product                    product_name     category  brl_price
0           1     Transponder AIS Maré Magnum  eletrônicos   33122.52
1           2       Transponder Furuno Marlin  eletrônicos   13998.15
2           3    Radar Furuno Pulse Leviathan  eletrônicos    9024.19
3           4       Rádio AIS Hydro Tidal Zen  eletrônicos    3381.88
4           5  Piloto Automático Furuno Storm  eletrônicos   23669.01

In [57]:
df_vendas_limpo.head()

   id_sale  id_client  id_product  qtd  brl_total  sale_date
0        0         42         105   11     3405.0 2023-10-09
1        1          3         136    9    16873.9 2024-09-15
2        2         25         139    7     9475.3 2024-08-13
3        4         20          23    5    55893.0 2023-03-02
4        5          8          57    4   451403.9 2024-12-02

In [58]:
# Conferir se os produtos em custos e produtos são consistentes
df_custos_unicos = df_custos_limpo[['id_product', 'product_name', 'category']].drop_duplicates()

df_produtos_unicos = df_produtos_limpo[['id_product', 'product_name', 'category']]

comparacao = pd.merge(
    df_custos_unicos, 
    df_produtos_unicos, 
    on='id_product', 
    how='outer', 
    suffixes=('_custos', '_produtos'), 
    indicator=True
)

inconsistencias = comparacao[
    (comparacao['_merge'] != 'both') |    
    (comparacao['product_name_custos'] != comparacao['product_name_produtos']) |
    (comparacao['category_custos'] != comparacao['category_produtos']) 
]

inconsistencias

Empty DataFrame
Columns: [id_product, product_name_custos, category_custos, product_name_produtos, category_produtos, _merge]
Index: []

In [59]:
print(df_produtos_limpo['category'].value_counts())
print(df_custos_limpo.groupby('category')['id_product'].nunique())

category
eletrônicos    50
propulsão      50
ancoragem      50
Name: count, dtype: int64
category
ancoragem      50
eletrônicos    50
propulsão      50
Name: id_product, dtype: int64

In [60]:
# Conferir se ocorrem duplicatas em vendas
df_vendas_limpo[df_vendas_limpo.duplicated(subset=['id_client', 'sale_date', 'id_product'], keep=False)].sort_values(['id_client','sale_date', 'id_product'])

      id_sale  id_client  id_product  qtd   brl_total  sale_date
387       395          3          29   11   381533.30 2023-02-27
6232     6300          3          29   15   520272.25 2023-02-27
5786     5846          6          93    7   703339.00 2023-07-11
8912     9007          6          93    8   803816.00 2023-07-11
1608     1628         11          41    1    10070.00 2024-03-22
2152     2176         11          41   11   116600.00 2024-03-22
5100     5155         24          86    9   799622.60 2023-01-05
6677     6752         24          86   15  1332704.65 2023-01-05
4401     4444         28         145    9    39149.00 2023-10-18
6929     7008         28         145    8    33059.05 2023-10-18
4128     4170         34          97    9  1218016.00 2024-10-06
6935     7014         34          97    5   676675.00 2024-10-06
1605     1625         38         130   14    58017.00 2023-08-26
4421     4464         38         130    9    35432.15 2023-08-26
753       763         42          75    9   280169.25 2023-11-21
8585     8678         42          75   10   311299.80 2023-11-21
5919     5981         42           6    2    23640.00 2023-11-26
6825     6904         42           6   13   145979.85 2023-11-26

In [61]:
# O preço entre vendas parece inconsistente, vou conferir
df_produtos_limpo[df_produtos_limpo['id_product'] == 29]

    id_product       product_name     category  brl_price
28          29  Rádio Simrad Orca  eletrônicos   36510.34

In [62]:
df_custos_limpo[df_custos_limpo['id_product'] == 29]

,id_product,product_name,category,start_date,end_date,usd_price
28,29,Rádio Simrad Orca,eletrônicos,2017-04-18,2022-03-28,11795.79
28,29,Rádio Simrad Orca,eletrônicos,2022-03-29,2025-08-10,7689.63
28,29,Rádio Simrad Orca,eletrônicos,2025-08-11,NaT,6703.20

In [63]:
df_precos = df_vendas_limpo.assign(
    preco_unitario = df_vendas_limpo['brl_total'] / df_vendas_limpo['qtd']
)[['id_sale', 'id_client', 'id_product', 'sale_date', 'qtd', 'brl_total', 'preco_unitario']]
df_precos[df_precos['id_product'] == 29].sort_values('preco_unitario')

,id_sale,id_client,id_product,sale_date,qtd,brl_total,preco_unitario
305,311,43,29,2023-11-29,1,34684.5,34684.500000
1217,1232,45,29,2024-10-23,1,34684.5,34684.500000
4356,4399,46,29,2023-01-11,1,34684.5,34684.500000
4654,4698,25,29,2024-03-02,1,34684.5,34684.500000
6099,6166,11,29,2024-06-05,7,242793.4,34684.771429
...,...,...,...,...,...,...,...
9415,9515,10,29,2023-06-24,5,182552.0,36510.400000
6011,6075,42,29,2023-09-30,5,182552.0,36510.400000
6406,6477,46,29,2023-05-07,5,182552.0,36510.400000
5684,5744,12,29,2024-08-24,2,73021.0,36510.500000
5038,5092,21,29,2023-03-05,2,73021.0,36510.500000

Aparentemente os valores com descontos são lançados diretos, então é impossivel prever os valores

# Migrar para Base de Dados Relacional

Atual:

df_clients_limpo: id_client, full_name, email, city, state

df_custos_limpo: id_product, product_name, category, start_date, end_date, usd_price

df_produtos_limpo: id_product, product_name, category, brl_price

df_vendas_limpo: id_sale, id_client, id_product, qtd, brl_total, sale_date

Base de dados:

clients: id_client, full_name, email, city, state

products: id_product, product_name, category, brl_price

import_costs: id_product, start_date, end_date, usd_price

sales: id_sale, id_client, id_product, qtd, brl_total, sale_date

In [66]:
df_custos_db = df_custos_limpo[['id_product', 'start_date', 'end_date', 'usd_price']]

string_conexao = 'postgresql://postgres:postgres@localhost:5435/LH_Nautical'
engine = create_engine(string_conexao)

print("1/4 Enviando Clientes...")
df_clientes_limpo.to_sql('clients', con=engine, if_exists='replace', index=False)

print("2/4 Enviando Produtos...")
df_produtos_limpo.to_sql('products', con=engine, if_exists='replace', index=False)

print("3/4 Enviando Custos de Importação...")
df_custos_db.to_sql('import_costs', con=engine, if_exists='replace', index=False)

print("4/4 Enviando Vendas...")
df_vendas_limpo.to_sql('sales', con=engine, if_exists='replace', index=False)

print("Tabelas enviadas com sucesso!")

1/4 Enviando Clientes...
2/4 Enviando Produtos...
3/4 Enviando Custos de Importação...
4/4 Enviando Vendas...
Tabelas enviadas com sucesso!

## Dolar

In [19]:
df_dolar = pd.read_csv('Datasets/usd_2023_2024.csv')

df_dolar = df_dolar.rename(columns={
    'cotacaoVenda': 'taxa_cambio',
    'dataHoraCotacao': 'taxa_cambio_data'
})

# Limpeza da cotação: troca vírgula por ponto e converte para float
df_dolar['taxa_cambio'] = (
    df_dolar['taxa_cambio']
    .str.replace(',', '.')
    .str.strip()
)
df_dolar['taxa_cambio'] = pd.to_numeric(df_dolar['taxa_cambio'], errors='coerce')

# Conversão da data para datetime e depois apenas data
df_dolar['taxa_cambio_data'] = pd.to_datetime(df_dolar['taxa_cambio_data']).dt.date

# Criar o intervalo de datas (calendário) de 2023-01-01 a 2024-12-31
calendario = pd.date_range(start='2023-01-01', end='2024-12-31').date
df_calendario = pd.DataFrame({'taxa_cambio_data': calendario})

# Left Join entre o calendário e os dados do dólar
df_final = pd.merge(df_calendario, df_dolar, on='taxa_cambio_data', how='left')

# Ordenar por data para garantir o preenchimento correto
df_final = df_final.sort_values('taxa_cambio_data')

# Passo A e B (LOCF): Preenche os valores nulos com o último valor válido anterior
df_final['taxa_cambio'] = df_final['taxa_cambio'].ffill()

# Trata o início do período (se o dia 01/01 for nulo, pega o primeiro valor válido do dataframe)
df_final['taxa_cambio'] = df_final['taxa_cambio'].bfill()

with engine.begin() as connection:

    df_final.to_sql('cambio_usd', con=connection, if_exists='replace', index=False,
                    dtype={'taxa_cambio': Numeric(10,4)})

    update_query = text("""
        UPDATE import_costs
        SET end_date = '2026-03-24'
        WHERE end_date IS NULL;
    """)
    connection.execute(update_query)

print("Migração e atualização concluídas com sucesso!")

Migração e atualização concluídas com sucesso!